### PR TITLE
Pairs of integers from m to n

### PR DESCRIPTION
**Pull request by doniambarita**
Implement a function that receives two integers m and n and generates a sorted list of pairs (a, b)

### CODE REVIEW

**Comment by AkshayNachappa** [comment]
Please write the driver code

**Comment by doniambarita** [comment]
what is the driver code? could you explain it to me?

**Comment by AkshayNachappa** [comment]
The lines of code that call the function so as to execute it.

**Comment by doniambarita** [comment]
Done

**Pull request merged**
